# Generated by Django 5.0.1 on 2025-01-13 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='alimony',
            field=models.BooleanField(default=False, verbose_name='Статья алиментов'),
        ),
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(error_messages={'unique': 'Такая категория уже существует'}, max_length=50, unique=True, verbose_name='Категория'),
        ),
    ]
