# Generated by Django 5.0.1 on 2025-04-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_expense_expense'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='expense',
            name='is_excessive',
            field=models.BooleanField(default=False, verbose_name='Необязательный'),
        ),
    ]
