# Generated by Django 5.0.1 on 2025-04-13 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_category_options_expense_is_excessive'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.PositiveIntegerField(verbose_name='Бюджет на месяц')),
            ],
            options={
                'verbose_name': 'Бюджет на месяц',
                'verbose_name_plural': 'Бюджет на месяц',
            },
        ),
    ]
