# Generated by Django 5.0.1 on 2025-05-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_category_user_alter_expense_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlybudget',
            name='budget',
            field=models.PositiveIntegerField(default=0, verbose_name='Бюджет на месяц'),
        ),
    ]
